package com.company.project.pojo;

import java.io.Serializable;

public class Holding extends HoldingKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.price
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.quantity
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    private Long quantity;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.time_stamp
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    private Long timeStamp;

    public Holding() {
    }

    public Holding(Double price, Long quantity, Long timeStamp) {
        // TODO: add parent
        this.price = price;
        this.quantity = quantity;
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.price
     *
     * @return the value of t_holding.price
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.price
     *
     * @param price the value for t_holding.price
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.quantity
     *
     * @return the value of t_holding.quantity
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.quantity
     *
     * @param quantity the value for t_holding.quantity
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.time_stamp
     *
     * @return the value of t_holding.time_stamp
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.time_stamp
     *
     * @param timeStamp the value for t_holding.time_stamp
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        // TODO: add parent
        return "Holding{" +
                "price=" + price +
                ", quantity=" + quantity +
                ", timeStamp=" + timeStamp +
                '}';
    }
}
