package com.company.project.pojo;

import java.io.Serializable;

public class Holding implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.asset_number
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Long assetNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.email
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.stock_symbol
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private String stockSymbol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.price
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.quantity
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Long quantity;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_holding.time_stamp
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Long timeStamp;

    public Holding() {}

    public Holding(
            Long assetNumber,
            String email,
            String stockSymbol,
            Double price,
            Long quantity,
            Long timeStamp) {
        this.assetNumber = assetNumber;
        this.email = email;
        this.stockSymbol = stockSymbol;
        this.price = price;
        this.quantity = quantity;
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.asset_number
     *
     * @return the value of t_holding.asset_number
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Long getAssetNumber() {
        return assetNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.asset_number
     *
     * @param assetNumber the value for t_holding.asset_number
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setAssetNumber(Long assetNumber) {
        this.assetNumber = assetNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.email
     *
     * @return the value of t_holding.email
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.email
     *
     * @param email the value for t_holding.email
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.stock_symbol
     *
     * @return the value of t_holding.stock_symbol
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public String getStockSymbol() {
        return stockSymbol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.stock_symbol
     *
     * @param stockSymbol the value for t_holding.stock_symbol
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setStockSymbol(String stockSymbol) {
        this.stockSymbol = stockSymbol == null ? null : stockSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.price
     *
     * @return the value of t_holding.price
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.price
     *
     * @param price the value for t_holding.price
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.quantity
     *
     * @return the value of t_holding.quantity
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.quantity
     *
     * @param quantity the value for t_holding.quantity
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_holding.time_stamp
     *
     * @return the value of t_holding.time_stamp
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_holding.time_stamp
     *
     * @param timeStamp the value for t_holding.time_stamp
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return "Holding{"
                + "assetNumber="
                + assetNumber
                + ", email='"
                + email
                + '\''
                + ", stockSymbol='"
                + stockSymbol
                + '\''
                + ", price="
                + price
                + ", quantity="
                + quantity
                + ", timeStamp="
                + timeStamp
                + '}';
    }
}
