package com.company.project.pojo;

public class Transaction extends TransactionKey {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_transaction.type
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_transaction.price
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_transaction.quantity
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    private Long quantity;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_transaction.type
     *
     * @return the value of t_transaction.type
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_transaction.type
     *
     * @param type the value for t_transaction.type
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_transaction.price
     *
     * @return the value of t_transaction.price
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_transaction.price
     *
     * @param price the value for t_transaction.price
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_transaction.quantity
     *
     * @return the value of t_transaction.quantity
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_transaction.quantity
     *
     * @param quantity the value for t_transaction.quantity
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }
}
