package com.company.project.pojo;

import java.io.Serializable;

public class Transaction implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.serial_number
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Long serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.type
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.email
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.stock_symbol
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private String stockSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.time_stamp
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Long timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.price
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transaction.quantity
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    private Long quantity;

    public Transaction() {
    }

    public Transaction(Long serialNumber, Integer type, String email, String stockSymbol, Long timeStamp, Double price, Long quantity) {
        this.serialNumber = serialNumber;
        this.type = type;
        this.email = email;
        this.stockSymbol = stockSymbol;
        this.timeStamp = timeStamp;
        this.price = price;
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.serial_number
     *
     * @return the value of t_transaction.serial_number
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.serial_number
     *
     * @param serialNumber the value for t_transaction.serial_number
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.type
     *
     * @return the value of t_transaction.type
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.type
     *
     * @param type the value for t_transaction.type
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.email
     *
     * @return the value of t_transaction.email
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.email
     *
     * @param email the value for t_transaction.email
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.stock_symbol
     *
     * @return the value of t_transaction.stock_symbol
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public String getStockSymbol() {
        return stockSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.stock_symbol
     *
     * @param stockSymbol the value for t_transaction.stock_symbol
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setStockSymbol(String stockSymbol) {
        this.stockSymbol = stockSymbol == null ? null : stockSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.time_stamp
     *
     * @return the value of t_transaction.time_stamp
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.time_stamp
     *
     * @param timeStamp the value for t_transaction.time_stamp
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.price
     *
     * @return the value of t_transaction.price
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.price
     *
     * @param price the value for t_transaction.price
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transaction.quantity
     *
     * @return the value of t_transaction.quantity
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transaction.quantity
     *
     * @param quantity the value for t_transaction.quantity
     *
     * @mbg.generated Thu Feb 02 02:24:03 EST 2023
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    @Override
    public String toString() {
        return "Transaction{" +
                "serialNumber=" + serialNumber +
                ", type=" + type +
                ", email='" + email + '\'' +
                ", stockSymbol='" + stockSymbol + '\'' +
                ", timeStamp=" + timeStamp +
                ", price=" + price +
                ", quantity=" + quantity +
                '}';
    }
}