package com.company.project.pojo;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public UserExample() {
    oredCriteria = new ArrayList<>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andEmailIsNull() {
      addCriterion("email is null");
      return (Criteria) this;
    }

    public Criteria andEmailIsNotNull() {
      addCriterion("email is not null");
      return (Criteria) this;
    }

    public Criteria andEmailEqualTo(String value) {
      addCriterion("email =", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotEqualTo(String value) {
      addCriterion("email <>", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailGreaterThan(String value) {
      addCriterion("email >", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailGreaterThanOrEqualTo(String value) {
      addCriterion("email >=", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLessThan(String value) {
      addCriterion("email <", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLessThanOrEqualTo(String value) {
      addCriterion("email <=", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLike(String value) {
      addCriterion("email like", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotLike(String value) {
      addCriterion("email not like", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailIn(List<String> values) {
      addCriterion("email in", values, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotIn(List<String> values) {
      addCriterion("email not in", values, "email");
      return (Criteria) this;
    }

    public Criteria andEmailBetween(String value1, String value2) {
      addCriterion("email between", value1, value2, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotBetween(String value1, String value2) {
      addCriterion("email not between", value1, value2, "email");
      return (Criteria) this;
    }

    public Criteria andPasswordIsNull() {
      addCriterion("password is null");
      return (Criteria) this;
    }

    public Criteria andPasswordIsNotNull() {
      addCriterion("password is not null");
      return (Criteria) this;
    }

    public Criteria andPasswordEqualTo(String value) {
      addCriterion("password =", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotEqualTo(String value) {
      addCriterion("password <>", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordGreaterThan(String value) {
      addCriterion("password >", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordGreaterThanOrEqualTo(String value) {
      addCriterion("password >=", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordLessThan(String value) {
      addCriterion("password <", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordLessThanOrEqualTo(String value) {
      addCriterion("password <=", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordLike(String value) {
      addCriterion("password like", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotLike(String value) {
      addCriterion("password not like", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordIn(List<String> values) {
      addCriterion("password in", values, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotIn(List<String> values) {
      addCriterion("password not in", values, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordBetween(String value1, String value2) {
      addCriterion("password between", value1, value2, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotBetween(String value1, String value2) {
      addCriterion("password not between", value1, value2, "password");
      return (Criteria) this;
    }

    public Criteria andFirstNameIsNull() {
      addCriterion("first_name is null");
      return (Criteria) this;
    }

    public Criteria andFirstNameIsNotNull() {
      addCriterion("first_name is not null");
      return (Criteria) this;
    }

    public Criteria andFirstNameEqualTo(String value) {
      addCriterion("first_name =", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotEqualTo(String value) {
      addCriterion("first_name <>", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameGreaterThan(String value) {
      addCriterion("first_name >", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
      addCriterion("first_name >=", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameLessThan(String value) {
      addCriterion("first_name <", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameLessThanOrEqualTo(String value) {
      addCriterion("first_name <=", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameLike(String value) {
      addCriterion("first_name like", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotLike(String value) {
      addCriterion("first_name not like", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameIn(List<String> values) {
      addCriterion("first_name in", values, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotIn(List<String> values) {
      addCriterion("first_name not in", values, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameBetween(String value1, String value2) {
      addCriterion("first_name between", value1, value2, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotBetween(String value1, String value2) {
      addCriterion("first_name not between", value1, value2, "firstName");
      return (Criteria) this;
    }

    public Criteria andLastNameIsNull() {
      addCriterion("last_name is null");
      return (Criteria) this;
    }

    public Criteria andLastNameIsNotNull() {
      addCriterion("last_name is not null");
      return (Criteria) this;
    }

    public Criteria andLastNameEqualTo(String value) {
      addCriterion("last_name =", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotEqualTo(String value) {
      addCriterion("last_name <>", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameGreaterThan(String value) {
      addCriterion("last_name >", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameGreaterThanOrEqualTo(String value) {
      addCriterion("last_name >=", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameLessThan(String value) {
      addCriterion("last_name <", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameLessThanOrEqualTo(String value) {
      addCriterion("last_name <=", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameLike(String value) {
      addCriterion("last_name like", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotLike(String value) {
      addCriterion("last_name not like", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameIn(List<String> values) {
      addCriterion("last_name in", values, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotIn(List<String> values) {
      addCriterion("last_name not in", values, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameBetween(String value1, String value2) {
      addCriterion("last_name between", value1, value2, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotBetween(String value1, String value2) {
      addCriterion("last_name not between", value1, value2, "lastName");
      return (Criteria) this;
    }

    public Criteria andBalanceIsNull() {
      addCriterion("balance is null");
      return (Criteria) this;
    }

    public Criteria andBalanceIsNotNull() {
      addCriterion("balance is not null");
      return (Criteria) this;
    }

    public Criteria andBalanceEqualTo(Double value) {
      addCriterion("balance =", value, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceNotEqualTo(Double value) {
      addCriterion("balance <>", value, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceGreaterThan(Double value) {
      addCriterion("balance >", value, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceGreaterThanOrEqualTo(Double value) {
      addCriterion("balance >=", value, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceLessThan(Double value) {
      addCriterion("balance <", value, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceLessThanOrEqualTo(Double value) {
      addCriterion("balance <=", value, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceIn(List<Double> values) {
      addCriterion("balance in", values, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceNotIn(List<Double> values) {
      addCriterion("balance not in", values, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceBetween(Double value1, Double value2) {
      addCriterion("balance between", value1, value2, "balance");
      return (Criteria) this;
    }

    public Criteria andBalanceNotBetween(Double value1, Double value2) {
      addCriterion("balance not between", value1, value2, "balance");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * t_user
   *
   * @mbg.generated do_not_delete_during_merge Mon Jan 23 01:03:00 EST 2023
   */
  public static class Criteria extends GeneratedCriteria {
    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * t_user
   *
   * @mbg.generated Mon Jan 23 01:03:00 EST 2023
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
