package com.company.project.mapper;

import com.company.project.pojo.Transaction;
import com.company.project.pojo.TransactionExample;
import com.company.project.pojo.TransactionKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TransactionMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    long countByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int deleteByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int deleteByPrimaryKey(TransactionKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int insert(Transaction row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int insertSelective(Transaction row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    List<Transaction> selectByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    Transaction selectByPrimaryKey(TransactionKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int updateByExampleSelective(
            @Param("row") Transaction row, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int updateByExample(
            @Param("row") Transaction row, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int updateByPrimaryKeySelective(Transaction row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_transaction
     *
     * @mbg.generated Mon Jan 23 01:03:00 EST 2023
     */
    int updateByPrimaryKey(Transaction row);
}
