#debug: true

spring:
  datasource:
    username: YOUR_DATABASE_USERNAME_HERE
    password: YOUR_DATABASE_PASSWORD_HERE
    url: jdbc:mysql://AWS_Endpoint_Here:AWS_PORT/DATABASE_NAME
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

mybatis:
  type-aliases-package: com.company.project.pojo
  mapper-locations: classpath:com/company/project/mapper/*.xml
