name: frontend_test_format

on:
  push:
    branches: [ main ]
    
  pull_request:
    paths:
      - frontend/**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd frontend/
        npm install

    - name: Build
      run: |
        cd frontend/
        npm run build
        
    - name: Run the tests and generate coverage report
      run: |
        cd frontend/
        npm test -- --coverage
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: install prettier 
      run: npm install --save-dev prettier
      
    - name: run the package
      run: npx prettier --write "**/*.tsx"

    - name: commit changes
      run: |
        git config --global user.email "code@format"
        git config --global user.name "frontend code format"
        git add .
        git commit -m "format with prettier"
  
    - name: Push Changes
      run: |
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}